# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: Alex Rawlings
email: alexander.rawlings@helsinki.fi
author: Alex Rawlings
description: > # "Write an awesome description for your new site here. 
  Personal webpage for Alex Rawlings astrophysicist University of Helsinki
copyright: 'Copyright &copy; 2023 Alex Rawlings. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  #- title: x-twitter
  #  url: https://twitter.com/alextrawlings
  - title: linkedin
    url: https://www.linkedin.com/in/alex-rawlings-008478119?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app
  - title: github
    url: https://github.com/alex-rawlings